#!/bin/bash
# Mock slicer for testing
# This script simulates PrusaSlicer/BambuStudio output

# Parse command line arguments to find the output file and support settings
OUTPUT_FILE=""
SUPPORT_ENABLED=false

prev_arg=""
for arg in "$@"; do
    if [[ "$prev_arg" == "--output" ]]; then
        OUTPUT_FILE="$arg"
    fi
    # Check for support material flag
    if [[ "$arg" == "--support-material=1" ]] || [[ "$arg" == "--support-material-auto=1" ]]; then
        SUPPORT_ENABLED=true
    fi
    prev_arg="$arg"
done

if [ -z "$OUTPUT_FILE" ]; then
    echo "Error: No output file specified" >&2
    exit 1
fi

# Set different values based on whether supports are enabled
if [ "$SUPPORT_ENABLED" = true ]; then
    # With supports: more material and time
    FILAMENT_USED="15.50"
    PRINT_TIME="1h 45m"
else
    # Without supports: less material and time
    FILAMENT_USED="12.34"
    PRINT_TIME="1h 23m"
fi

# Create mock gcode output with typical slicer comments
cat > "$OUTPUT_FILE" <<EOF
; generated by Mock Slicer 2.0.0
; total filament used [g] = $FILAMENT_USED
; estimated printing time (normal mode) = $PRINT_TIME
;
; layer_height = 0.2
; perimeters = 2
; fill_density = 15%
; support_material = $SUPPORT_ENABLED
;
G28 ; home all axes
G1 Z0.2 F3000 ; move to first layer height
; Begin printing
G1 X10 Y10 E1.5 F1800
G1 X20 Y10 E3.0 F1800
; End printing
M104 S0 ; turn off hotend
M140 S0 ; turn off bed
M107 ; turn off fan
M84 ; disable motors
EOF

echo "Mock slicer completed successfully. Output: $OUTPUT_FILE (supports: $SUPPORT_ENABLED)" >&2
exit 0
